### PR TITLE
Remove code to guess power for items with 0, since items can have zero power

### LINKED ISSUE #3219: incorrect pulverize yields in mafia data
Image

mafia thinks Shadow Skin gives you wads, though there is a question mark on it. it actually gives you powders! 

Image

i will post any more i encounter in here as well :-) thank you for reading and i hope you all are having a merry crimbo

### PR DESCRIPTION
**Pull request by gausie**
Fixes #3219 

This is throwing off pulverization result readouts. Nowadays we know the power of equipment almost instantly, and we don't have as much use for inaccurate pulverization data.

### CODE REVIEW

File: src/net/sourceforge/kolmafia/persistence/EquipmentDatabase.java [hunk 1]
```diff
@@ -771,38 +771,23 @@ private static int derivePulverization(final int id) {
...
-      }
-    }
 
-    int power = EquipmentDatabase.getPower(id);
-    if (power <= 0) {
-      // power is unknown, derive from requirement (which isn't always accurate)
-      pulver |= YIELD_UNCERTAIN;
-      String req = EquipmentDatabase.statRequirements.get(id);
+    // Null mods might suggest no enchantments at all, which would imply
+    // that this pulverizes to uselgiess powder.  However, there are many items
```
Comment (midgleyc) [inline src/net/sourceforge/kolmafia/persistence/EquipmentDatabase.java]:
```suggestion
    // that this pulverizes to useless powder.  However, there are many items
```
how did that happen?

File: src/net/sourceforge/kolmafia/persistence/EquipmentDatabase.java [hunk 2]
```diff
@@ -771,38 +771,23 @@ private static int derivePulverization(final int id) {
...
-        power = 0;
-      } else {
-        int colonIndex = req.indexOf(":");
-
-        if (colonIndex != -1) {
-          String reqValue = req.substring(colonIndex + 1).trim();
-          power = StringUtilities.parseInt(reqValue) * 2 + 30;
-        }
-      }
+    if (mods != null) {
```
Comment (midgleyc) [inline src/net/sourceforge/kolmafia/persistence/EquipmentDatabase.java:782]: do beer goggles still correctly not pulverize to useless powder with this new code?

Comment (gausie) [reply src/net/sourceforge/kolmafia/persistence/EquipmentDatabase.java:782]: I don't understand. Why would they?

File: src/net/sourceforge/kolmafia/persistence/EquipmentDatabase.java (hunk 1 above)
Comment (gausie) [reply src/net/sourceforge/kolmafia/persistence/EquipmentDatabase.java]: Since becoming a parent of two I am becoming my mother and constantly typoing basic words

File: src/net/sourceforge/kolmafia/persistence/EquipmentDatabase.java (hunk 2 above)
Comment (midgleyc) [reply src/net/sourceforge/kolmafia/persistence/EquipmentDatabase.java:782]: you seem to have removed the code that added twinkly nature to equipment with no mods

the comment says they are twinkly

Comment (gausie) [reply src/net/sourceforge/kolmafia/persistence/EquipmentDatabase.java:782]: Added a test to show that this is fine. I see your confusion now, I removed a branch of code that essentially did `A | B | B`, the second B is redundant.

Comment (midgleyc) [reply src/net/sourceforge/kolmafia/persistence/EquipmentDatabase.java:782]: ah cool, thanks

**Review by midgleyc — APPROVED** [review]
