### PR TITLE
Fix further issues supplying a "bandersnatch" value for the Peridot choice

### LINKED ISSUE #2904: ChoiceUtilities.parseChoices fails to parse the Peridot of Peril zone noncombat
The new tracking for the Peridot of Peril is great and is working well. One issue I've encountered, however, is that I'd like to be able to handle the peridot something like this: 
```typescript
setProperty("choiceAdventure1557", `1&bandersnatch=${$monster`goblin flapper`.id}`);
adv1($location`An Unusually Quiet Barroom Brawl`);
```
because most of the time when I adventure with the peridot of peril, I know where I'm adventuring and want to fight a non-conditional monster, so I can set my expectations ahead of time.

I'm successfully able to do this with some adventures, like the Machine Elf's duplicator:
```
Preference choiceAdventure1125 changed from 1&iid=9199 to 1&iid=11378
Preference lastAdventure changed from Barf Mountain to The Deep Machine Tunnels

[485] The Deep Machine Tunnels
Preference lastEncounter changed from garbage tourist to Fuchsia Into Your Consciousness
Encounter: Fuchsia Into Your Consciousness
Took choice 1119/4: duplicate one food, booze, spleen or potion
choice.php?whichchoice=1119&option=4&pwd
Preference lastEncounter changed from Fuchsia Into Your Consciousness to A Threat of Two
Encounter: A Threat of Two
Preference encountersUntilDMTChoice changed from 0 to 49
Preference lastDMTDuplication changed from 2296 to 2297
Took choice 1125/1: (secret choice)
choice.php?whichchoice=1125&option=1&iid=11378&pwd
You acquire an item: pickled bread
Preference lastAdventureContainer changed from place.php?whichplace=airport_stench to place.php?whichplace=dmt
Preference _concoctionDatabaseRefreshes changed from 2349 to 2350
```
but when I try to do something analogous for the Peridot of Peril, I get an error:
```
Preference choiceAdventure1557 changed from to 1&bandersnatch=2252

Visit to Speakeasy: An Unusually Quiet Barroom Brawl in progress...
Preference lastAdventure changed from Noob Cave to An Unusually Quiet Barroom Brawl

[61] An Unusually Quiet Barroom Brawl
Preference _perilLocations changed from to 558
Choice option 1557/1 is not available.
```
(when the choice adventure opened in my browser there was nothing weird about the adventure, I selected the goblin flapper I wanted and it went off without a hitch)

EDIT:
this is on kolmafia revision 28512, which is the latest as of this posting.

### PR DESCRIPTION
**Pull request by gausie**
- **Fix peridot parsing by widening choice parsing appropriately**
- **Linting for ChoiceUtilities class**
- **Formatting**
- **Quick fix of semi-unrelated issue**
- **Support filling extra hidden fields with the extra field in choiceAdventureXXX**

Re-fixes #2904

Whielw e were able to successfully parse the options for the choice in #2905, the choice adventure validation code was not ready to deal with multiple forms that submit the same option with a different value'd hidden input. This is essentially an alternative way of producing a single option with an extra select input. Seems reasonable to support generically so we do that.

There are some forms one could imagine in future (where mutliple overloads for a single decision form have differing sets of hidden input field), but we can deal with those if and when such a form is introduced.

### CODE REVIEW

File: src/net/sourceforge/kolmafia/utilities/ChoiceUtilities.java [hunk 1]
```diff
@@ -408,6 +407,71 @@ private static Set<String> extractTextInputChoices(String form) {
...
+    Matcher m = FORM_PATTERN.matcher(responseText);
+    while (m.find()) {
+      String form = m.group();
+      if (isNonChoiceForm(form)) continue;
+      Matcher optMatcher = OPTION_PATTERN1.matcher(form);
+      if (!optMatcher.find()) {
+        continue;
+      }
+
+      // Collect all the text inputs from this form
```
Comment (midgleyc) [inline src/net/sourceforge/kolmafia/utilities/ChoiceUtilities.java:427]:
```suggestion
      // Collect all the hidden inputs from this form
```

**Review by midgleyc — APPROVED** [review]
